# Generated by Django 4.2.23 on 2025-10-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_audio_file_post_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_file',
            new_name='image',
        ),
    ]
