# Generated by Django 4.2.23 on 2025-11-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='아티스트명')),
                ('audio_file', models.FileField(upload_to='music/audio/', verbose_name='오디오 파일')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/covers/', verbose_name='커버 이미지')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='장르')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='재생 시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_works', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '음악',
                'verbose_name_plural': '음악들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 날짜')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_likes', to='mypage.music', verbose_name='음악')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '음악 좋아요',
                'verbose_name_plural': '음악 좋아요들',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'music')},
            },
        ),
    ]
